

"""
QUEST: Quantum Evaluation of Software Trust

Phase 4:
Autonomous Multi-Agent Verification Framework

Module:
Base Agent

Purpose:
Defines the common foundation for all QUEST verification agents.

Every autonomous agent must:
- receive evidence
- perform independent reasoning
- generate structured findings
- provide confidence scores
"""


from abc import ABC, abstractmethod
from dataclasses import dataclass, asdict
from typing import Dict, List


@dataclass
class AgentFinding:
    """
    Standard output representation generated by every QUEST agent.
    """

    agent_name: str
    component: str
    finding: str
    severity: str
    confidence: float
    evidence: Dict


class BaseAgent(ABC):
    """
    Abstract foundation for all QUEST autonomous verification agents.

    Ensures all agents follow the same reasoning interface.
    """


    def __init__(
        self,
        name: str
    ):
        self.name = name


    @abstractmethod
    def analyze(
        self,
        context: Dict
    ) -> List[AgentFinding]:
        """
        Executes agent-specific reasoning.

        Each specialized agent implements this method.
        """

        pass


    def create_finding(
        self,
        component: str,
        finding: str,
        severity: str,
        confidence: float,
        evidence: Dict
    ) -> AgentFinding:
        """
        Creates a standardized QUEST agent result.
        """

        confidence = max(
            0,
            min(confidence, 1)
        )

        return AgentFinding(
            agent_name=self.name,
            component=component,
            finding=finding,
            severity=severity,
            confidence=round(
                confidence,
                5
            ),
            evidence=evidence
        )


    def serialize(
        self,
        findings: List[AgentFinding]
    ) -> List[Dict]:
        """
        Converts agent findings into JSON-compatible format.
        """

        return [
            asdict(finding)
            for finding in findings
        ]


    def calculate_confidence(
        self,
        signals: List[float]
    ) -> float:
        """
        Calculates confidence from multiple reasoning signals.
        """

        if not signals:
            return 0

        normalized = [
            max(0, min(value, 1))
            for value in signals
        ]

        return round(
            sum(normalized) / len(normalized),
            5
        )